 access_key = "AKIA3NBQJVBPB7S6NZTQ"
 secret_key = "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"
 region = "us-east-1"
 vpc_cidr  = "10.100.0.0/16"
 vpc_name = "terraform1"
 igw_name = "t_igw"
 env = "prod"
